# Generated by Django 5.1.6 on 2025-02-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_user_is_bidder_remove_user_is_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='auction_images/default.jpg', upload_to='auction_images/'),
        ),
        migrations.AddField(
            model_name='auction',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
