# Generated by Django 5.1.6 on 2025-03-01 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_description_auction_image_auction_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('condition_summary', models.TextField()),
                ('engine_status', models.CharField(choices=[('Good', 'GOood'), ('Fair', 'Fair'), ('Poor', 'poor')], max_length=50)),
                ('body_condition', models.CharField(choices=[('No Damage', 'No Damage'), ('Minor Scratches', 'Minor Scratches'), ('Dents', 'Dents')], max_length=50)),
                ('tire_condition', models.CharField(choices=[('New', 'New'), ('Used - Good', 'Used - Good'), ('Worn Out', 'Worn Out')], max_length=50)),
                ('interior_condition', models.TextField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
