# Generated by Django 5.1.6 on 2025-03-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_created_at_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
